create or replace view vw_api_regioes_resumo as
select r.cd_regiao_saude,
       r.nm_regiao_saude,
       r.cd_macrorregiao_saude,
       r.nm_macrorregiao_saude,
       g.qt_municipio,
       r.nr_ano_competencia,
       r.nr_mes_competencia,
       r.cd_competencia,
       r.qt_internacao_nova,
       r.qt_obito,
       r.qt_dia_permanencia_soma,
       r.vl_aprovado_internacao_nova_soma,
       r.qt_hospital_com_internacao,
       r.qt_paciente_dia_estimado,
       r.qt_leito_sus,
       r.qt_capacidade_teorica_leito_dia,
       r.qt_populacao_ibge_2022,
       r.qt_internacao_residente_observada,
       r.qt_internacao_residente_na_propria_regiao,
       r.qt_evasao_intrastadual_observada,
       r.qt_internacao_icsap_residente_observada,
       r.qt_internacao_recebida_outra_regiao_sp,
       r.qt_internacao_recebida_fora_sp,
       r.tx_internacao_residente_observada_por_100_mil,
       r.pc_evasao_intrastadual_observada,
       r.pc_atracao_assistencial,
       r.pc_icsap_no_total_internacao_residente_observada,
       r.tx_icsap_residente_observada_por_10_mil,
       r.pc_tmh,
       r.vl_cmi,
       r.nr_permanencia_media,
       r.nr_iph_estimado,
       r.pc_iph_estimado,
       r.qt_internacao_media_historica,
       r.qt_ano_historico,
       r.nr_indice_sazonalidade,
       r.pc_variacao_sazonal,
       r.st_indice_sazonalidade,
       r.nr_indice_ipca,
       r.nr_fator_correcao_ipca,
       r.cd_competencia_preco_referencia,
       r.vl_aprovado_internacao_nova_real_soma,
       r.vl_cmi_real
  from mart_indicador_regiao_mensal r
  join dim_geografia_regiao g
    on g.cd_regiao_saude = r.cd_regiao_saude;

comment on table vw_api_regioes_resumo is
  'Resumo mensal das 62 regioes para mapa e visao executiva. A view le indicadores e denominadores persistidos na Gold; nao recalcula indicadores.';
